#!/bin/bash

TEN_S=0
ONE_M=0
FIFTEEN_M=0

while getopts "123" opt; do
  case "$opt" in
  1)
    TEN_S=1
    ;;
  2)
    ONE_M=1
    ;;
  3)
    FIFTEEN_M=1
    ;;
  esac
done

if [[ $TEN_S -eq 1 ]]; then
  echo "$(curl -s 127.0.0.1/1/summary | jq '.hashrate.total[0]')"
elif [[ $ONE_M -eq 1 ]]; then
  echo "$(curl -s 127.0.0.1/1/summary | jq '.hashrate.total[1]')"
elif [[ $FIFTEEN_M -eq 1 ]]; then
  echo "$(curl -s 127.0.0.1/1/summary | jq '.hashrate.total[2]')"
else
  echo "error: supply an argument"
fi
